
# Ansible managed
#
# http://prometheus.io/docs/operating/configuration/

global:
  scrape_interval: 15s
  scrape_timeout: 10s
  evaluation_interval: 15s

  external_labels:
    environment: fhmoo8pu0hg9u7er5daj.auto.internal




rule_files:
  - /etc/prometheus/rules/*.rules


scrape_configs:
  - job_name: prometheus
    metrics_path: /metrics
    static_configs:
    - targets:
      - fhmoo8pu0hg9u7er5daj.auto.internal:9090
  - job_name: node
    file_sd_configs:
    - files:
      - /etc/prometheus/file_sd/node.yml
  - job_name: 'node_exporter'
    static_configs:
      - targets: ['localhost:9100']  # Замените на IP-адрес и порт вашего Node Exporter, если он работает не на локальном хосте
  - job_name: blackbox-http
    metrics_path: /probe
    params:
      module:
      - http_2xx
    relabel_configs:
    - source_labels:
      - __address__
      target_label: __param_target
    - source_labels:
      - __param_target
      target_label: instance
    - replacement: localhost:9115
      target_label: __address__
    static_configs:
    - targets:
      - http://84.201.129.186:30003

scrape_config_files:
  - scrapes/*
