version: '3.8'

services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./www:/var/www
      - ./php/php.ini:/usr/local/etc/php/conf.d/40-custom.ini
    healthcheck:
      test: ["CMD", "curl", "-f", "http://nginx", "|", "grep", "works"]
      interval: 30s
      timeout: 10s
      retries: 3
    depends_on:
      - nginx

  nginx:
    image: nginx:1.27
    volumes:
      - ./nginx/dev.conf:/etc/nginx/conf.d/default.conf
      - ./www:/var/www
    ports:
      - "80:80"
