apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: my-app-release-my-app-chart-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: manual  # Укажите имя StorageClass
