apiVersion: v1
kind: Service
metadata:
  name: {{ include "my_app_chart.fullname" . }}
  labels:
    {{- include "my_app_chart.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      nodePort: {{ .Values.service.nodePort }}
  selector:
    app: {{ include "my_app_chart.name" . }}

