Vagrant.configure("2") do |config|
  # Указываем базовый образ (Ubuntu 18.04)
  config.vm.box = "bento/ubuntu-18.04"
  
  # Настройка виртуальной машины
  config.vm.provider "virtualbox" do |vb|
    vb.memory = "1024"
    vb.cpus = 2
  end

  # Команды для выполнения при создании ВМ
  config.vm.provision "shell", inline: <<-SHELL
    # Обновление пакетов
    sudo apt-get update
    
    # Установка python3 и python3-pip
    sudo apt-get install -y python3 python3-pip

    # Установка библиотек psycopg2 и Django
    pip3 install psycopg2 Django
  SHELL

  # Копирование пустого файла на ВМ
  config.vm.provision "file", source: "empty_file.txt", destination: "/home/vagrant/empty_file.txt"
end
