apiVersion: v1
kind: PersistentVolume
metadata:
  name: my-app-release-my-app-chart-pv
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 1Gi
  hostPath:
    path: /mnt/data  # Убедитесь, что этот путь существует на вашем узле
  storageClassName: manual  # Если используете `storageClassName` в PVC
